export const LOAD_MOVIES = 'LOAD_MOVIES';
export const LOAD_MOVIES_ERROR = 'LOAD_MOVIES_ERROR';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';

export const SET_MOVIES = 'SET_MOVIES';
export const SET_TOTAL_RESULTS = 'SET_TOTAL_RESULTS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_QUERY = 'SET_QUERY';

export const LOAD_MOVIE_DETAIL = 'LOAD_MOVIE_DETAIL';
export const LOAD_MOVIE_DETAIL_SUCCESS = 'LOAD_MOVIE_DETAIL_SUCCESS';
export const LOAD_MOVIE_DETAIL_ERROR = 'LOAD_MOVIE_DETAIL_ERROR';